# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(60, 80, 521, 501))
        self.input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input.setText("")
        self.input.setObjectName("input")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(630, 80, 501, 501))
        self.output.setText("")
        self.output.setObjectName("output")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1170, 110, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1170, 260, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(60, 650, 1101, 231))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 600, 1101, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1170, 510, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1170, 410, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(810, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1170, 360, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1170, 60, 111, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1170, 210, 111, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1170, 160, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1170, 310, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1170, 460, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.Read)
        self.pushButton_2.clicked.connect(MainWindow.Text_yolo)
        self.pushButton_3.clicked.connect(MainWindow.FRCNN)
        self.pushButton_3.clicked.connect(MainWindow.Text_frcnn)
        self.pushButton_5.clicked.connect(MainWindow.Text_mask)
        self.pushButton_5.clicked.connect(MainWindow.Mask_RCNN)
        self.pushButton_2.clicked.connect(MainWindow.YOLOV3)
        self.pushButton_4.clicked.connect(MainWindow.DeeplabV3)
        self.pushButton_4.clicked.connect(MainWindow.Text_deeplab)
        self.pushButton_6.clicked.connect(MainWindow.Camera)
        self.pushButton_7.clicked.connect(MainWindow.Video)
        self.pushButton_8.clicked.connect(MainWindow.Text_yolo4)
        self.pushButton_8.clicked.connect(MainWindow.YOLOV4)
        self.pushButton_9.clicked.connect(MainWindow.Text_det)
        self.pushButton_9.clicked.connect(MainWindow.EfficientDet)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Open Image"))
        self.pushButton_2.setText(_translate("MainWindow", "YOLO v3"))
        self.pushButton_3.setText(_translate("MainWindow", "Faster RCNN"))
        self.pushButton_4.setText(_translate("MainWindow", "DeeplabV3+"))
        self.label.setText(_translate("MainWindow", "Fire & Smoke Detection Platform"))
        self.label_2.setText(_translate("MainWindow", "Original"))
        self.label_3.setText(_translate("MainWindow", "Detection Result"))
        self.pushButton_5.setText(_translate("MainWindow", "Mask_RCNN"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Mode"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Image"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Local Camera"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Phone Camera"))
        self.pushButton_6.setText(_translate("MainWindow", "Open Camera"))
        self.pushButton_7.setText(_translate("MainWindow", "Open Video"))
        self.pushButton_8.setText(_translate("MainWindow", "YOLO v4"))
        self.pushButton_9.setText(_translate("MainWindow", "EfficientDet"))
